export const LOG_IN = "USER:LOG_IN";
export const LOG_OUT = "USER:LOG_OUT";
export const ERROR_LOGIN = "USER:ERROR_LOGIN";
export const CHANGE_LOADING = "USER:CHANGE_LOADING";
export const CHECK_LOGIN = "USER:CHECK_LOGIN";
export const GET_USERS = "USER:GET_USERS";
export const GET_USER = "USER:GET_USER";

export const POPULATE_USER_TABLE = "USERS:POPULATE_USER_TABLE";
export const CHANGE_LOADING_USERS = "USERS:CHANGE_LOADING_USERS";

export const POPULATE_FEED_TABLE = "SETTINGS:POPULATE_USER_TABLE";
export const CHANGE_LOADING_FEEDS = "SETTINGS:CHANGE_LOADING_FEEDS";

export const POPULATE_VIDEO_TABLE = "VIDEOS:POPULATE_VIDEO_TABLE";
export const CHANGE_LOADING_VIDEOS = "VIDEOS:CHANGE_LOADING_VIDEOS";

export const GET_ROUTES = "ROUTES:GET_ROUTES";
export const POPULATE_ROUTE_TABLE = "ROUTES:POPULATE_ROUTE_TABLE";
export const CHANGE_LOADING_ROUTES = "ROUTES:CHANGE_LOADING_ROUTES";

export const POPULATE_RATING_TABLE = "RATINGS:POPULATE_RATING_TABLE";
export const CHANGE_LOADING_RATINGS = "RATINGS:CHANGE_LOADING_RATINGS";

export const POPULATE_PAGINATION = "PAGINATION:POPULATE_PAGINATION";
export const CHANGE_PAGINATION_BY_NUMBER = "PAGINATION:CHANGE_PAGINATION_BY_NUMBER";
export const CHANGE_PAGINATION_BY_ARROW = "PAGINATION:CHANGE_PAGINATION_BY_ARROW";
export const CHANGE_PAGINATION_COUNT = "PAGINATION:CHANGE_PAGINATION_COUNT";
export const CHANGE_TABLE_AMOUNT = "PAGINATION:CHANGE_TABLE_AMOUNT";

export const RESET_PAGINATION = "PAGINATION:RESET_PAGINATION";

export const GET_VIDEO_DATA = "VIDEO:GET_VIDEO_DATA";
export const GET_VIDEO_DATA_LOADING = "VIDEO:GET_VIDEO_DATA_LOADING";

export const GET_VOERTUIGEN = "VOERTUIGEN:GET_VOERTUIGEN";
export const POPULATE_VOERTUIGEN_TABLE = "VOERTUIGEN:POPULATE_VOERTUIGEN_TABLE";
export const CHANGE_LOADING_VOERTUIGEN = "VOERTUIGEN:CHANGE_LOADING_VOERTUIGEN";

export const GET_PLANNINGEN = "PLANNINGEN:GET_PLANNINGEN";
export const CHANGE_LOADING_PLANNINGEN = "PLANNINGEN:CHANGE_LOADING_PLANNINGEN";

export const GET_PLANNINGENUSER = "PLANNINGENUSER:GET_PLANNINGENUSER";
export const CHANGE_LOADING_PLANNINENGUSER = "PLANNINGENUSER:CHANGE_LOADING_PLANNINENGUSER";

export const GET_PLANNING = "PLANNING:GET_PLANNING";
export const INSERT_PLANNING = "PLANNING:INSERT_PLANNING";
export const CHANGE_LOADING_INSERT_PLANNING = "PLANNING:CHANGE_LOADING_INSERT_PLANNING";
export const CHANGE_LOADING_PLANNING = "PLANNING:CHANGE_LOADING_PLANNING";
export const CHANGE_SUCCESS_INSERT = "PLANNING:CHANGE_SUCCESS_INSERT";
export const ERROR_INSERT = "PLANNING:ERROR_INSERT";


